# Настройки RPath:
# Должна быть прописана переменная ${INSTALL_PREFIX}.
# Библиотеки ищутся в ${CMAKE_INSTALL_RPATH}=${INSTALL_PREFIX}/lib.

if(NOT INSTALL_PREFIX)
  message(FATAL_ERROR "You must set INSTALL_PREFIX before including RPath.txt!")
endif(NOT INSTALL_PREFIX)

set(CMAKE_INSTALL_PREFIX ${INSTALL_PREFIX})
set(CPACK_PACKAGING_INSTALL_PREFIX ${INSTALL_PREFIX})

set(CMAKE_SKIP_BUILD_PATH false)
set(CMAKE_BUILD_WITH_INSTALL_RPATH false)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH true)
set(CMAKE_INSTALL_RPATH "${INSTALL_PREFIX}/lib")
set(CMAKE_INSTALL_NAME_DIR ${CMAKE_INSTALL_RPATH})

